import type { Dict } from './index';

export const ja: Dict = {
  meta: {
    title: 'ネルソン水嶋のこと｜“あいだ”の編集者',
    description:
      'コンテンツで誰かと誰かをつなぐ“あいだ”の編集者、ネルソン水嶋（水嶋健）のサイト。編集・執筆、多文化共生、アプリ開発——半生と取り組みをまとめています。',
  },
  nav: {
    about: 'ネルソンのこと',
    projects: '制作実績',
    company: '会社概要',
    contact: 'ご相談',
    services: 'お仕事相談',
  },
  toolbar: {
    fontSize: '文字の大きさ',
    fontSmall: '小さく',
    fontNormal: '標準',
    fontLarge: '大きく',
    language: 'ことば',
  },
  hero: {
    titleHtml:
      '<span class="marker">“あいだ”で、<br class="sm:hidden" />つくって、つなぐ。</span>',
    lead: 'ネルソン水嶋です。作ってきたものは、記事、冊子、アプリ…と、いろいろありますが、目的は、いつも、<strong>“あいだ”でつくってつなぐこと</strong>。<span class="mt-3 block"><span class="marker-umi">ベトナムでは日本とのあいだを</span>、<span class="marker-akatsuchi">沖永良部島では外国人と日本人とのあいだを</span>、<span class="marker-gajumaru">そしていまは、東京で、出身者と島ルーツのあいだを</span>。</span>',
    cta: 'ネルソンのことを知る',
    tags: ['社会教育士', '多文化共生マネージャー', 'Google AI Professional 認定', '元システムエンジニア', 'ライター・編集者', '沖永良部島ルーツ', 'ドリアンマン'],
  },
  news: {
    heading: '最近のこと',
  },
  services: {
    heading: 'できること',
    lead: '頼めることは、大きく3つです。どれも“あいだ”の編集という同じ仕事の、道具が違うだけだと思っています。',
    viewWorks: '実績を見る',
    note: '“あいだ”でつくってつないでいるうちに、できることも増えました。「こんなことで困っている」と聞かせてもらえれば、意外なところでお役に立てるかもしれません。お気軽に<a href="#contact" class="text-akatsuchi underline underline-offset-4">お声がけ</a>ください。',
    items: [
      {
        title: '掘る・書く・編む',
        quals: 'ライター・編集者',
        examples: ['取材・リサーチをして記事や冊子にまとめたい', '広報を読み物にしたい', 'メディアを立ち上げたい'],
        price: '記事制作：5万円〜／冊子（16P編集）：30万円〜（全体ディレクション：50万円〜）',
      },
      {
        title: 'つなぐ',
        quals: '社会教育士／多文化共生マネージャー',
        examples: ['メディアやイベントを介した外国人住民との橋渡し', '地域プロジェクトの伴走', '講演・研修'],
      },
      {
        title: 'つくる',
        quals: 'Google AI Professional 認定／元システムエンジニア',
        examples: ['業務やまちの課題をアプリで見える化して解決したい', '業務効率化などでAI活用を相談したい', '郷土グッズをつくりたい'],
        price: 'プロトタイプ制作：10万円〜（2026年12月末までは特別価格5万円〜）',
      },
    ],
  },
  about: {
    heading: 'ネルソンのこと',
    lead: '1984年に大阪で生まれ育ち、東京、ベトナム、沖永良部島（奄美群島）、そして2026年、再び東京に。<br />仕事の仕方は“デジタル百姓”。詳しい年表は<a href="https://nenpyo-sandy.vercel.app/t/fa0fefff-88f4-47bd-8b67-9aae674d47fc" target="_blank" rel="noopener" class="text-akatsuchi underline underline-offset-4">こちら</a>（generated by じぶん年表）',
    phases: [
      {
        era: '第1期',
        years: '2006〜2011（22〜27歳）',
        title: '東京／SE・Twitter大喜利主宰者',
        body: 'システムエンジニアとして、システム構築や要件定義などのITスキルの土台を築く。Twitterで<a href="https://ascii.jp/elem/000/000/487/487685/" target="_blank" rel="noopener" class="text-akatsuchi underline underline-offset-4">大喜利の主宰</a>にのめり込み、帰宅中の電車内で出題とつっこみを繰り返す日々を送る。大喜利仲間と実際に会い、画面と現実の“あいだ”は超えられるという、コミュニティづくりの原体験を得る。憧れていた会社への転職に失敗。後先考えずに退職して無職になる。時間ができたので、人生初の海外へ。',
      },
      {
        era: '第2期',
        years: '2011〜2019（27〜35歳）',
        title: 'ベトナム／ブロガー・ライター・編集者',
        body: 'ベトナム旅行中、現地に住む日本人から誘われ、転職と同時に移住。期待と現実にギャップを感じて、4ヶ月で退職して再び無職に。「おもしろいことは自分でやるしかない」と痛感し、現地情報ブログ「べとまる」を立ち上げる。ベトナムと日本の“あいだ”を企画と発信でつなぐ。ドリアンの皮を装備して<a href="https://vietmaru.com/2015/06/durian-man/" target="_blank" rel="noopener" class="text-akatsuchi underline underline-offset-4">街を練り歩いた記事</a>がバズるほか、記事の<a href="https://dailyportalz.jp/b/rookie2014/result.htm" target="_blank" rel="noopener" class="text-akatsuchi underline underline-offset-4">賞</a>を3度獲得、ライターに。その後、編集長として世界各地のライター30人超と情報サイトの創刊に携わり、編集経験を培う。',
      },
      {
        era: '第3期',
        years: '2020〜2026（36〜42歳）',
        title: '沖永良部島／多文化共生・社会教育・記者',
        body: 'ウェブ記事で島でのベトナム人技能実習生の失踪を知ったことと、祖母がいる島とのつながりを守りたかった思いが重なり、沖永良部島へ移住。合同会社オトナキを起業し、社会教育士・多文化共生マネージャー・新聞記者などの顔で、外国人と地域の“あいだ”をつなぐ<a href="https://www.clair.or.jp/j/multiculture/docs/2ac56a354594612505b21d3defd30c9a_2.pdf" target="_blank" rel="noopener" class="text-akatsuchi underline underline-offset-4">ツール</a>開発・冊子制作・イベント企画・試験対策サポート、<a href="https://www.nankainn.com/news/local/%E6%96%B9%E8%A8%80%E7%B6%99%E6%89%BF%E6%B4%BB%E5%8B%95%E3%83%AC%E3%83%9D%E3%83%BC%E3%83%88%E3%82%92%E5%88%8A%E8%A1%8C%E3%80%80%E5%B3%B6%E3%83%A0%E3%83%8B%E3%82%80%E3%82%93%E3%81%A1%E3%82%83%E3%81%AE" target="_blank" rel="noopener" class="text-akatsuchi underline underline-offset-4">方言</a>や<a href="https://www.nankainn.com/news/education/%e6%98%94%e3%81%a8%e4%bb%8a%e3%81%a7%e5%90%8d%e5%89%8d%e9%81%95%e3%81%86%ef%bc%81%ef%bc%9f%e3%80%80%e9%9b%86%e8%90%bd%e5%90%8d%e3%81%ae%e7%94%b1%e6%9d%a5%e5%ad%a6%e3%81%b6%e3%80%8c%e3%82%8f%e3%81%a9" target="_blank" rel="noopener" class="text-akatsuchi underline underline-offset-4">郷土史</a>などの文化継承活動に関わる。500人超の島民を取材する。',
      },
      {
        era: '第4期',
        years: '2026（42歳）〜',
        title: '東京／島と都会とルーツの“あいだ”へ',
        body: '島で暮らす中で自分と同じくルーツを辿って来た人たちとの出会いを通し、世代交代に伴う地縁の希薄化と、だからこそつながろうとする人間の意志を感じる。“あいだ”に立つ存在が必要だと思い、15年ぶりに再び東京へ。島ルーツの探究を続けながら、奄美群島にゆかりのある飲食店（小さなコミュニティ）をまとめた<a href="https://nommunity-map.vercel.app/" target="_blank" rel="noopener" class="text-akatsuchi underline underline-offset-4">アプリ</a>開発などに取り組む。SE、ブロガー、記者、社会教育士——肩書きはそのときどきで変わっても、やっていることはずっと、“あいだ”で、つくって、つなぐ。',
      },
    ],
  },
  projects: {
    heading: 'おもなプロジェクト（制作実績）',
    lead: '「事業内容」と言うと堅いので、これまで形にしてきたプロジェクトを並べます。それぞれ、読み物として書いています。',
    categories: {
      mediaOps: {
        label: 'メディア運営・伴走支援',
        description: '現場に飛び込んで、想いに寄り添い、メディアを立ち上げ、育ててきたもの。',
      },
      contrib: {
        label: '寄稿・連載・現地記者',
        description: '外部メディアへの寄稿や連載、地元紙・NHKなどの現地記者として書いてきたもの。',
      },
      tabunka: {
        label: '多文化共生・社会教育・まちづくり',
        description: '多文化共生マネージャーや社会教育士などの専門知識を学んだ上で、違う文化や時代を生きてきた人どうしが同じまちで暮らすためのものづくり（冊子を含む）に取り組んでいます。',
      },
      digital: {
        label: 'アプリ開発',
        description: 'AIでたった数時間でアプリがつくれる時代。システムエンジニア時代に培った設計思考を活かして、編集者や社会教育士としての知見や実践をアプリに落とし込む。',
      },
    },
  },
  company: {
    heading: '会社概要',
    lead: '法人のお取引は「合同会社オトナキ」でお受けしています（個人でお受けすることも可能です）。',
    toggle: '会社情報を見る',
    labels: {
      name: '商号',
      philosophy: '理念',
      representative: '代表',
      founded: '設立',
      locationHq: '本社',
      locationTokyo: '東京オフィス',
      business: '事業内容',
    },
  },
  contact: {
    heading: 'ご相談・おしゃべり',
    lead: 'お仕事のご依頼から、「ちょっと聞きたい」くらいの温度感まで、お気軽にどうぞ。<br /><span class="text-xs">※原則、休日を除いた3日以内に返信いたします。<br />※内容（スパムや商材営業など）によっては返信いたしかねます。</span>',
    workNote:
      'お仕事のご依頼も、もちろん受け付けています。執筆・編集、多文化共生や地域の企画、アプリ開発など、お見積もり・ご予算のご相談からで大丈夫です。法人とのお取引は合同会社オトナキとしてお受けします。',
    topics: [
      '執筆や編集のご相談',
      '多文化共生や地域課題に関するプロジェクト',
      'アプリやAI活用のアイデア',
      '島ルーツについてのおしゃべり',
    ],
    form: {
      name: 'お名前',
      email: 'メールアドレス',
      message: 'ご用件',
      submit: '送信する',
    },
  },
  footer: {
    tagline: '“あいだ”で、つくって、つなぐ。',
  },
  a11y: {
    toTop: 'いちばん上へ戻る',
  },
};
